org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Gradle'a hangi JDK'yı kullanacağını net bir şekilde söyle, diğer ayarları yok say.
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr