// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QJuHuBUfa_PpijC9YPfZ7C7VgwG4lW4',
    appId: '1:153185743492:web:595b3f89e336390a7d08d1',
    messagingSenderId: '153185743492',
    projectId: 'halisaharakipapp',
    authDomain: 'halisaharakipapp.firebaseapp.com',
    storageBucket: 'halisaharakipapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyfJIj6qHs5Ub89UobFNrv2vnBoFSJa4',
    appId: '1:153185743492:android:bbe086557fd8a31b7d08d1',
    messagingSenderId: '153185743492',
    projectId: 'halisaharakipapp',
    storageBucket: 'halisaharakipapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFeHzrwH1pWvO4KRS1hNqueY7NcefP2zA',
    appId: '1:153185743492:ios:386964da2038b57a7d08d1',
    messagingSenderId: '153185743492',
    projectId: 'halisaharakipapp',
    storageBucket: 'halisaharakipapp.firebasestorage.app',
    iosBundleId: 'com.example.halisaharakipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFeHzrwH1pWvO4KRS1hNqueY7NcefP2zA',
    appId: '1:153185743492:ios:386964da2038b57a7d08d1',
    messagingSenderId: '153185743492',
    projectId: 'halisaharakipapp',
    storageBucket: 'halisaharakipapp.firebasestorage.app',
    iosBundleId: 'com.example.halisaharakipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QJuHuBUfa_PpijC9YPfZ7C7VgwG4lW4',
    appId: '1:153185743492:web:36d7fb582ff101137d08d1',
    messagingSenderId: '153185743492',
    projectId: 'halisaharakipapp',
    authDomain: 'halisaharakipapp.firebaseapp.com',
    storageBucket: 'halisaharakipapp.firebasestorage.app',
  );
}
